services:
  webserver:
    build: ./webserver
    volumes:
      - ./webserver/app:/app
      - ./webserver/static/uploads:/app/static/uploads
      - ./model:/app/model
      - ./dataset:/dataset
    ports:
      - "5000:5000"
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - image_analyzer

  image_analyzer:
    build: ./image_analysis_server
    volumes:
      - ./model:/app/model
    env_file:
      - .env 
    restart: unless-stopped
