services:
  image_analysis_server:
    container_name: image_analysis_server
    image: alpine:latest
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./image_analysis_server/:/app/
    env_file:
      - .env 
