FROM python:3.9-slim

WORKDIR /app

COPY ./app /app
COPY requirements.txt /app

RUN apt-get update && apt-get install -y \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip --ignore-installed --no-cache-dir -r requirements.txt

RUN chmod +x /app/retrain.sh

EXPOSE 5000

CMD ["python", "app.py"]
